### ISSUE TITLE
Querying tasks by parent_id is not working for some projects

### ISSUE THREAD

**Issue by gianlucadonato** [NeokingdomDAO/odoo#12]
## Current Behavior
I'm seeing this error when querying some tasks and including their parent_id:
``` 
"Unexpected token '<', ...\" \n        <html>\n   \"... is not valid JSON"
```

## Expected Behavior
It should be possible to query project tasks and get their parent_id without errors.

## Steps to Reproduce
If I query a project by project_id 22 and filter its tasks by user_id 12 then graphql returns an error.

Example:
```
{
  ProjectProject(domain: [["id", "in", [22]]]) {
    id
    name
    tasks(domain: [["user_id", "=", 12]]) {
      id
      name
      parent_id {
        id
        name
      }
    }
  }
}
```

But if I run the same query for project_id 27 then it works. 
So it seems that for some tasks odoo graphql breaks when asking for the `parent_id`. 

A similar and more simple example can also be replicated by doing this query:

```
{
  ProjectTask(domain: [["user_id", "=", 12]]) {
    id
    name
    parent_id {
      id
    }
  }
}
```

**Comment by PeterSchwarzHPI** [comment]
After investigating quite a bit I found out that there is an issue with the user_id field.
However, it doesn't make sense to go even deeper into this topic as this field will be removed anyways.
So: instead of user_id just use user_idS and everything works well.
