### ISSUE TITLE
Bug in Odoo wallet login

### ISSUE THREAD

**Issue by gianlucadonato** [NeokingdomDAO/odoo#15]
I noticed a bug in the odoo login when using the jrpc session. 
Steps to reproduce:
1. Login on the dapp via wallet 
    - Eth address + pwd are used to authenticate
    - The first login works well, and the following jrpc api calls are correctly made 
    - The dapp correctly retrieve the user uid 

2. After ~10min, the dapp perform the same jrpc query as always to retrieve the uid, but this time odoo returns false for some reason. 
This is the [api call](https://github.com/NeokingdomDAO/dapp/blob/c77167e36479348cb7955ce8159fc3378076d484/lib/odooClient.ts#L61 ) which is called with the following params: 
```
url = https://odoo.neokingdom.org/jsonrpc 
db =  neokingdomdao
 username = eth address 
pwd = cookie pwd
```

The usr + pwd params are always correct (I already checked), but after ~10min from the initial login, odoo returns 200 status response with UID false, and this is causing the dapp to fail all the subsequent jrpc requests.

**Comment by PeterSchwarzHPI** [comment]
Just found the following in the odoo standard code. So I assume the session is already outdated and a fully new one should be fetched. I think you might use the wrong authentication method then.

<img width="1262" alt="image" src="https://user-images.githubusercontent.com/3071446/235311969-33296350-d5fc-4902-8a0b-6e851be0bc09.png">

**Comment by gianlucadonato** [comment]
@PeterSchwarzHPI I'm not using either of the two endpoints though. What the dapp is using to authenticate is a jrpc `call` to `https://odoo.neokingdom.org/jsonrpc ` using `{ service: "common", method: "login" }` as parameters, and `db, uid, password` as arguments. 

Not sure which endpoint is then being internally routed and used by odoo.
Should I use a different auth method? If so, can you provide more details? thanks

**Comment by PeterSchwarzHPI** [comment]
I finally found the issue. The reason is that with the "get signing token" method you get a JWT token which is only valid for 10 minutes. So if you "re-authenticate" make sure to have a valid token first.
